### ISSUE TITLE
Parsing international prefix without "+" may confuse phonelib

### ISSUE THREAD

**Issue by delphaber** [daddyz/phonelib#87]
Hi,

`391` is a [valid italian mobile phone prefix.](https://it.wikipedia.org/wiki/Prefissi_telefonici_dei_cellulari_italiani)

So `3911234567` should be a valid mobile number, but (I think) phonelib `v0.6.5` reads the leading `39` as the international prefix for Italy.

In fact:
`Phonelib.parse('3911234567', 'IT').national(false)` returns `11234567` instead of `3911234567`
`Phonelib.parse('3911234567', 'IT').valid?` returns `false`

If I add the international prefix, it works:
`Phonelib.parse('+393911234567', 'IT').national(false)` returns `3911234567`
`Phonelib.parse('+393911234567', 'IT').valid?` returns `true`
`Phonelib.parse('+393911234567', 'IT').type` returns `:mobile`

Tell me if I can help you with more information.

Thanks!

**Comment by delphaber** [comment]
`392` (another valid italian mobile prefix) works succefully

`Phonelib.parse('3921234567', 'IT').type` returns `:mobile` (so, it's valid)

**Comment by daddyz** [comment]
@delphaber fixed in 0.6.6. Thanks for reporting

**Comment by delphaber** [comment]
Thanks!

**Comment by huyderman** [comment]
This problem is still present for some Norwegian mobile phone numbers starting with `47` (4xx xx xxx is a [valid number range](https://en.wikipedia.org/wiki/Telephone_numbers_in_Norway) for cell phones.)

```rb
> Phonelib.parse '47161746', 'NO'
=> #<Phonelib::Phone:0x00000001aeb540
 @data=
  {"NO"=>
    {:id=>"NO",
     :country_code=>"47",
     :international_prefix=>"00",
     :leading_zero_possible=>"true",
     :main_country_for_code=>"true",
     :mobile_number_portable_region=>"true",
     :national=>"161746",
     :format=>{:pattern=>"(\\d+)(\\d{3})(\\d{4})", :format=>"$1 $2 $3"},
     :valid=>[],
     :possible=>[:toll_free]}},
 @extension="",
 @national_number="161746",
 @original="47161746",
 @sanitized="47161746">
```
This should be the same as:
```rb
> Phonelib.parse '+4747161746', 'NO'
=> #<Phonelib::Phone:0x00000002696570
 @data=
  {"NO"=>
    {:id=>"NO",
     :country_code=>"47",
     :international_prefix=>"00",
     :leading_zero_possible=>"true",
     :main_country_for_code=>"true",
     :mobile_number_portable_region=>"true",
     :national=>"47161746",
     :format=>{:pattern=>"([489]\\d{2})(\\d{2})(\\d{3})", :leading_digits=>"[489]", :format=>"$1 $2 $3"},
     :valid=>[:mobile],
     :possible=>[:premium_rate, :toll_free, :shared_cost, :voip, :personal_number, :voicemail, :fixed_or_mobile]}},
 @extension="",
 @national_number="47161746",
 @original="+4747161746",
 @sanitized="4747161746">
```

It doesn't seem to affect all numbers starting with `47` though, as some other numbers I tested worked just fine.

I've tested on `phonelib => 0.6.8`
